### ISSUE TITLE
ESP32-PICO with OV2640 camera

### ISSUE THREAD

**Issue by abtabrizi** [Marek128b/Esp32-mini-btb-connect#2]
Hi @Marek128b, 

Thanks for sharing the project. I have some questions about the chip you used in the project. 
What is the best way to connect with you (email, etc.,)?

**Comment by Marek128b** [comment]
what questions do you have about the chip? <br> the best way to connect with me is here on github because if others have the same questions or have solutions the can see the answers here or help you as well.

**Comment by abtabrizi** [comment]
@Marek128b can the ESP chip on your board interface with a camera? in other words, is it possible to integrate a camera with the current design.

**Comment by Marek128b** [comment]
it chould be possible most pins of the ESP32 are broken out on the connectors. you might need to change some configurations in the library for your camera but other than that you should not have problems with it. Please note that i have never worked with camera modules appart from the esp32 cam. but looking at the schematic of the esp32 cam it should be possible.

**Comment by abtabrizi** [comment]
i see! would it look something like below? i found this schematic online and it uses the same chip as in your design. the board has a 2.4G ceramic antenna + DVP connecting to a [OV2640 camera](https://www.pishop.ca/product/esp32-cam-camera-module-based-on-esp32/). however, it seems that it can be only powered using battery. 

![scheme](https://github.com/Marek128b/Esp32-mini-btb-connect/assets/134088680/ecebe9e8-cc80-4bf7-8636-f1a256e51b1f)
